### ISSUE TITLE
DB deployment error

### ISSUE THREAD

**Issue by gabrielwolf** [valentinocossar/trellis-database-and-uploads-migration#10]
Hi there, I'm trying to get the addon working, unfortunately while trying to push the DB from dev to staging I get the following error:

$ ./bin/database.sh staging dock2dekoration.de push

PLAY [Push dock2dekoration.de database from development to staging] ***************************************************
TASK [Gathering Facts] ************************************************************************************************
Enter passphrase for key '/Users/develop/.ssh/id_rsa':
ok: [staging_host]
TASK [Abort if environment variable is equal to development] **********************************************************
skipping: [staging_host]
TASK [Check if dock2dekoration.de folder exists] **********************************************************************
ok: [staging_host -> 192.168.50.5]
TASK [Abort if dock2dekoration.de folder doesn't exists] **************************************************************
System info:
  Ansible 2.4.2.0; Darwin
  Trellis at "Update `vagrant_box_version` to `>= 201801.02.0`"
---------------------------------------------------
ERROR: dock2dekoration.de is not a valid site name (dock2dekoration.de folder
does not exist).
fatal: [staging_host]: FAILED! => {"changed": false}
	to retry, use: --limit @/Users/develop/Websites/dock2dekoration.de/trellis/database-push.retry

PLAY RECAP ************************************************************************************************************
staging_host               : ok=2    changed=0    unreachable=0    failed=1

Ansible version: 2.4.2.0
OS name and version: High Sierra 10.13.2
Trellis version: 1.0.0-rc.2

My [config files](https://gist.github.com/gabrielwolf/188904b17aa4f1743eb2e8924145067e).

What might be wrong?

Any hints greatly appreciated!
Gabriel

**Comment by valentinocossar** [comment]
Hi, have you tried to replace your staging host (`dock2dekoration.testserver.berlin`) with the IP of the server?

**Comment by gabrielwolf** [comment]
Sorry for the delay. I tried the IP, but without luck. I finally got it done in combining the settings you propose in the docs almost literally and the existing hostname. A  "Replace your_server_hostname and add these lines to your existing configuration" would have been the shortcut :-)

Thank you for this project, it is a great tool!

**Comment by valentinocossar** [comment]
Glad to hear that you've solved the problem. I think the problem was related to the parameter `ansible_connection=local` in your development host file.

Thank you!
