### ISSUE TITLE
Getting MODULE FAILURE when backing up Staging DB

### ISSUE THREAD

**Issue by fernandoagarcia** [valentinocossar/trellis-database-and-uploads-migration#13]
## Submit a feature request or bug report

- [x] I've read the guidelines for Contributing to this project in the README.md
- [] This is a feature request
- [X] This is a bug report
- [X] This request isn't a duplicate of an [existing issue](https://github.com/valentinocossar/trellis-database-uploads-migration/issues)
- [X] I've read the [README](https://github.com/valentinocossar/trellis-database-uploads-migration/blob/master/README.md) and followed its instructions (if applicable)

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

When running the ./bin/database.sh for staging it fails because its looking for a '/current' directory. Running ./bin/database.sh for development works fine.

**Please describe your local environment:**

Ansible version: 2.5.3

OS name and version: OS Sierra 10.12.6

Trellis version: 1.0.0-rc.2

**Where did the bug happen? Development or remote servers?**

Remove Server (Staging)

**Has the bug already been solved or discussed on [Ansible issues page](https://github.com/ansible/ansible/issues)?**

No

**Other relevant information:**

`
System info:
  Ansible 2.5.3; Darwin
  Trellis version (per changelog): "Bump Ansible `version_tested_max` to 2.5.3"
---------------------------------------------------
MODULE FAILURE
Traceback (most recent call last):
  File "/tmp/ansible_y6kwZS/ansible_module_command.py", line 248, in <module>
    main()
  File "/tmp/ansible_y6kwZS/ansible_module_command.py", line 192, in main
    os.chdir(chdir)
OSError: [Errno 2] No such file or directory:
'/srv/www/micegroups.com/current'

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/srv/www/micegroups.com/current'
fatal: [206.189.210.91]: FAILED! => {"changed": false, "module_stdout": "", "rc": 1}
	to retry, use: --limit @/Users/digital/git/micegroups.com/trellis/database-backup.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************
206.189.210.91             : ok=3    changed=0    unreachable=0    failed=1   
`

**Comment by valentinocossar** [comment]
Hi, sorry but right now I'm busy with some work. As soon as I can I'll look into this issue and update the tool (if necessary) to make it compatible with the latest versions of Ansible (>= 2.5.0).

Also could be a good idea adding somewhere in the README a notice like "Tested up to Ansible 2.X.X".

Thank you for the feedback.

**Comment by valentinocossar** [comment]
Hi, I've tested the tool with every Ansible version (up to version 2.6.1) and I can't replicate the issue. Is the local VM started? And where are you running the `./bin/database.sh` command?
